import type { AnalysisReport } from "@/types";
import { ConfidenceBadge } from "./ConfidenceBadge";

export function ReportView({ report }: { report: AnalysisReport }) {
  return (
    <div className="space-y-6">
      <section>
        <h2 className="mb-2 text-lg font-semibold">Overview</h2>
        <p className="text-sm leading-relaxed opacity-90">{report.overview}</p>
      </section>

      <section>
        <h2 className="mb-3 text-lg font-semibold">Per-Channel Analysis</h2>
        <div className="space-y-3">
          {report.per_channel.map((c) => (
            <div
              key={c.channel_name}
              className="rounded-lg border border-border bg-[hsl(var(--muted))] p-4"
            >
              <div className="mb-1 flex items-center justify-between">
                <h3 className="font-medium">{c.channel_name}</h3>
                <ConfidenceBadge level={c.confidence} />
              </div>
              <p className="text-sm opacity-90">{c.interpretation}</p>
              <p className="mt-1 text-xs italic opacity-60">{c.confidence_reasoning}</p>
            </div>
          ))}
        </div>
      </section>

      {report.structural_risks.length > 0 && (
        <section>
          <h2 className="mb-3 text-lg font-semibold">Structural Risks</h2>
          <ul className="space-y-2">
            {report.structural_risks.map((r, i) => (
              <li key={i} className="rounded-lg border border-border p-3 text-sm">
                <span className="font-medium">{r.title}</span> — {r.description}
              </li>
            ))}
          </ul>
        </section>
      )}

      <section>
        <h2 className="mb-3 text-lg font-semibold">Recommendations</h2>
        <div className="space-y-3">
          {report.recommendations.map((rec, i) => (
            <div key={i} className="rounded-lg border border-border p-4">
              <div className="mb-1 flex items-center justify-between">
                <span className="font-medium">{rec.action}</span>
                <ConfidenceBadge level={rec.confidence} />
              </div>
              <p className="text-sm opacity-90">{rec.rationale}</p>
              {rec.dependencies.length > 0 && (
                <p className="mt-1 text-xs opacity-60">
                  Depends on: {rec.dependencies.join(", ")}
                </p>
              )}
            </div>
          ))}
        </div>
      </section>

      <p className="text-xs opacity-40">
        Generated by {report.metadata.agent_model} · prompt{" "}
        {report.metadata.prompt_version}
      </p>
    </div>
  );
}
