"""Initial analysis pipeline (design doc 5.1).

Stages:
  1. Parse       -> MMMSummary (deterministic, in app.parsers)
  2. Retrieve    -> knowledge base context (app.rag)
  3. Analyze     -> AnalysisReport via the analysis agent (LLM, structured)
  4. Cache       -> stored on the session by the API layer

If no LLM key is configured, ``_heuristic_report`` produces a deterministic
report so the end-to-end skeleton is demoable before wiring the API key.
"""

from __future__ import annotations

from datetime import UTC, datetime

from app.agents import prompts
from app.core.llm import LLMClient, LLMNotConfigured, get_agent_llm
from app.models.analysis_report import (
    AnalysisReport,
    ChannelAnalysis,
    Citation,
    Recommendation,
    ReportMetadata,
    Risk,
    ValidationStep,
)
from app.models.mmm_summary import MMMSummary
from app.parsers import mmm_parser
from app.rag.retriever import retriever

PROMPT_NAME = "analysis"


def _now() -> str:
    return datetime.now(UTC).isoformat()


def _retrieval_query(summary: MMMSummary) -> str:
    channels = ", ".join(c.name for c in summary.channels)
    issues = ", ".join(i.code for i in summary.detected_issues)
    return (
        f"{summary.model_type} MMM with channels: {channels}. "
        f"Detected features: {issues or 'none'}."
    )


async def run(
    mmm_output, session_id: str, llm: LLMClient | None = None
) -> tuple[MMMSummary, AnalysisReport]:
    summary = mmm_parser.parse(mmm_output)
    chunks = retriever.retrieve(_retrieval_query(summary))

    llm = llm or get_agent_llm()
    try:
        report = await _llm_report(summary, chunks, session_id, llm)
    except LLMNotConfigured:
        report = _heuristic_report(summary, session_id)
    return summary, report


async def _llm_report(summary, chunks, session_id, llm) -> AnalysisReport:
    system = prompts.load(PROMPT_NAME)
    kb = "\n\n".join(f"[{c.chunk_id}] {c.text}" for c in chunks) or "(none retrieved)"
    user = (
        f"MMM_OUTPUT (parsed summary):\n{summary.model_dump_json(indent=2)}\n\n"
        f"KNOWLEDGE_BASE:\n{kb}"
    )
    report = await llm.structured(system, user, AnalysisReport, max_tokens=4096)
    report.session_id = session_id
    report.metadata = ReportMetadata(
        agent_model=llm._model,
        prompt_version=prompts.version_tag(PROMPT_NAME),
        generated_at=_now(),
    )
    return report


def _heuristic_report(summary: MMMSummary, session_id: str) -> AnalysisReport:
    """Deterministic fallback report used when no LLM key is configured."""
    ranked = summary.ranked_channels()
    per_channel = [
        ChannelAnalysis(
            channel_name=c.name,
            interpretation=(
                f"{c.name} shows an estimated ROI of {c.roi_point:.2f} "
                f"(95% CI {c.roi_ci[0]:.2f}-{c.roi_ci[1]:.2f}) and contributes "
                f"{c.contribution_pct * 100:.1f}% of attributed outcome."
            ),
            confidence="low" if c.ci_width >= c.roi_point else "medium",
            confidence_reasoning=(
                "Wide credible interval relative to the point estimate."
                if c.ci_width >= c.roi_point
                else "Interval is reasonably tight relative to the estimate."
            ),
            citations=[Citation(source_type="mmm_output", reference=c.name)],
        )
        for c in summary.channels
    ]
    risks = [
        Risk(
            title=f"{issue.code} ({issue.channel})" if issue.channel else issue.code,
            description=issue.detail,
            severity="medium",
            citations=[
                Citation(source_type="mmm_output", reference=issue.channel or "model")
            ],
        )
        for issue in summary.detected_issues
    ]
    top = ranked[0] if ranked else "the top channel"
    recommendations = [
        Recommendation(
            action=f"Prioritize incremental budget toward {top} pending saturation checks.",
            priority="high",
            rationale="Highest ROI point estimate among modeled channels.",
            confidence="medium",
            dependencies=["Confirm the channel is not near saturation."],
            citations=[Citation(source_type="mmm_output", reference=top)],
        )
    ]
    validation = [
        ValidationStep(
            step="Run a geo lift test on the top-ranked channel.",
            rationale="Validate the model's ROI estimate against a causal benchmark.",
        )
    ]
    return AnalysisReport(
        session_id=session_id,
        overview=(
            f"This {summary.model_type} model covers {summary.n_channels} channels over "
            f"{summary.data_span_weeks or 'an unspecified number of'} weeks. "
            f"By ROI point estimate, channels rank: {', '.join(ranked)}. "
            "NOTE: generated by the deterministic fallback (no LLM key configured)."
        ),
        per_channel=per_channel,
        structural_risks=risks,
        recommendations=recommendations,
        validation_suggestions=validation,
        metadata=ReportMetadata(
            agent_model="heuristic-fallback",
            prompt_version="none",
            generated_at=_now(),
        ),
    )
